import io.github.fvarrui.javapackager.gradle.PackageTask
import io.github.fvarrui.javapackager.model.LinuxConfig
import io.github.fvarrui.javapackager.model.WindowsConfig
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.fvarrui:javapackager:1.7.2'
    }
}
plugins {
    id 'idea'
    id 'java-library'
    id 'application'
}
apply plugin: 'io.github.fvarrui.javapackager.plugin'

version '4.2.1'

dependencies {
    implementation 'fr.flowarg:openlauncherlib:3+'
    implementation 'fr.flowarg:azuljavadownloader:1.0.2'
    implementation 'fr.flowarg:flowmultitools:1.4.4'
}
jar {
    manifest {
        attributes 'Main-Class': 'fr.gamity.installer.Main', 'SplashScreen-Image': 'splash.png'
    }
}

def jarFile = tasks.named('jar').get().archiveFile.get().asFile

def issFile = file("$buildDir/installer.iss")
def outputDir = file("$buildDir/installer")

tasks.register('generateIss') {
    dependsOn jar

    doLast {
        outputDir.mkdirs()

        issFile.text = """
[Setup]
AppName=Gamity Launcher
AppVersion=${project.version}
DefaultDirName={pf}\\Gamity Launcher
DefaultGroupName=Gamity Launcher
OutputDir=${outputDir}
OutputBaseFilename=GamityInstaller
Compression=lzma
SolidCompression=yes
SetupIconFile="../../GamityInstaller.ico"

[Files]
Source: "${jarFile.absolutePath}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\\..\\java\\win64\\*"; DestDir: "{app}\\jre"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\\Gamity Launcher"; Filename: "{app}\\jre\\bin\\javaw.exe"; Parameters: "-jar ${jarFile.name}"
Name: "{commondesktop}\\Gamity Launcher"; Filename: "{app}\\jre\\bin\\javaw.exe"; Parameters: "-jar ${jarFile.name}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Créer un raccourci bureau"; GroupDescription: "Options :"
"""
    }
}

tasks.register('buildInstaller', Exec) {
    dependsOn 'generateIss'

    commandLine 'iscc', "${buildDir}/installer.iss"
}