import io.github.fvarrui.javapackager.gradle.PackageTask
import io.github.fvarrui.javapackager.model.LinuxConfig
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.fvarrui:javapackager:1.7.2'
    }
}
plugins {
    id 'idea'
    id 'java-library'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

apply plugin: 'io.github.fvarrui.javapackager.plugin'

version '4.2.1'

dependencies {
    implementation 'fr.flowarg:openlauncherlib:3+'
    implementation 'fr.flowarg:azuljavadownloader:1.0.2'
    implementation 'fr.flowarg:flowmultitools:1.4.4'
}

application {
    getMainClass().set('fr.gamity.installer.Main')
}

shadowJar {
    manifest {
        attributes 'SplashScreen-Image': 'splash.png'
    }
}

def issFile = file("${buildDir}/installer.iss")
def outputDir = file("${buildDir}/installer")
tasks.register('generateIss') {
    dependsOn "shadowJar"

    doLast {
        def jarName = shadowJar.archiveFileName.get()

        issFile.text = """
[Setup]
AppName=Gamity Launcher
AppVersion=${project.version}
DefaultDirName={pf}/Gamity Launcher
DefaultGroupName=Gamity Launcher
OutputDir=./installer
OutputBaseFilename=GamityInstaller_${project.version}
Compression=lzma
SolidCompression=yes
SetupIconFile=../../GamityInstaller.ico

[Files]
Source: "./libs/${jarName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "../../GamityInstaller.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "../../java/win64/*"; DestDir: "{app}/jre"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\\Gamity Launcher"; Filename: "{app}/jre/bin/javaw.exe"; Parameters: "-jar ${jarName}"; WorkingDir: "{app}"; IconFilename: "{app}/GamityInstaller.ico"

Name: "{commondesktop}\\Gamity Launcher"; Filename: "{app}/jre/bin/javaw.exe"; Parameters: "-jar ${jarName}"; WorkingDir: "{app}"; IconFilename: "{app}/GamityInstaller.ico"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Créer un raccourci bureau"; GroupDescription: "Options :"
"""
    }
}
tasks.register('buildWin', Exec) {
    dependsOn 'generateIss'

    workingDir file("${buildDir}")

    commandLine 'wine',
            'C:/Program Files (x86)/Inno Setup 6/ISCC.exe',
            'installer.iss'
}

tasks.register('buildLinux', PackageTask) {
    dependsOn "build"
    displayName = "Gamity Launcher"
    mainClass = 'fr.gamity.installer.Main'
    bundleJre = true
    generateInstaller = true
    platform = io.github.fvarrui.javapackager.model.Platform.linux
    jrePath = file('../java/linux64')
    linuxConfig(({
        generateDeb = true
        generateRpm = false
        generateAppImage = false
        pngFile = file('../GamityInstaller.png')
    } as Closure<LinuxConfig>))
}

tasks.register('buildAll'){
    dependsOn 'buildLinux', 'buildWin'
}